### ISSUE TITLE
Dinosaur meta issue :sauropod: 

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-operator#37]
What I'd like to do starting this week (and in this order)

1. [x] **1.** Figure out container size issue (e.g., new builds of flux are causing backoff on pull for minikube) (update, use ssh to pull first)
2. [x] **2.** Test the new RESTFul API with and without a command, this will be the requirement to merge #34 
3. [x]  **2.** Remove build for container examples from here, should be in flux-hpc instead.
4. [x] **3.** Test a better way to get networking within the pods and avoid the restart #36 
5. [x] **4.** Blow up our currently inefficient docs and make a new, rendered web interface (preparing to add tutorials / user docs / examples)
6. [x] **5.** Small bugfixes in UI interface https://github.com/flux-framework/flux-restful-api/issues/27
7. [x] **6.** Start container-izing known HPC workflows, adding to https://github.com/rse-ops/flux-hpc from https://lc.llnl.gov/hpc-cloud-docs/ and https://lc.llnl.gov/confluence/display/HIF/On-Prem+Cloud+Services (thanks @milroy !) 
8. [ ] **7.** (not required, but would be really fun if time allows) Go back to Flux RESTFul API and add bells and whistles, possibly multi-user case and Go SDK (definitely Go SDK).

I don't know if the above is all feasible (e.g., if I hit some big technical issue I might be slower than I want) but I think maybe? I'm kind of thrilled everyone is at SC22 this week because meetings are cancelled and I can work and swing from the chandelier all week! Just kidding. :partying_face: Or rather, just program in my happy place and go for good runs without worrying about said meetings. <3

**Comment by vsoch** [comment]
Okay I finished all but the Go SDK - will have a separate issue for that.
