### ISSUE TITLE
Testing Meta Issue

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-operator#51]
As we get #49 finished up I want to elaborate on needs for testing

 - [x] #49 handles basic headless tests - e.g., we can provide a headless job, and verify successful output (if deterministic) and if not, container exit codes == 0.
   - [ ] However, this doesn't yet handle jobs that require a certain number of tasks or flags. I know `--test-size=4` doesn't seem to work. I think the `-ompi=openmpi@5` is technically an option so it should. @grondo could you advise here?
 - [ ] We also need testing for the web UI views, and this will be harder and possibly require something like selenium. We need to be sure that entrypoint continues to function (and I don't break it)
 - [ ] For within Go we need both unit tests and e2e tests. I have a lot of examples for these, and it mostly will be about deciding when t's priority to do.
