### ISSUE TITLE
Tweaks to Configuration: Next TODO

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-operator#8]
- [x] use `flux-sample-[0-<size>] as the hosts in the broker.toml (should this be reflected in /etc/hosts too?) #9 
- [ ] figure out how to set /etc/hosts properly (k8 needs to write /etc/resolv.conf so having a volume there is weird)
- [x] change permissions/ownership on the curve cert
- [x] set the default command to start flux 

A few ideas here for setting hosts: https://stackoverflow.com/questions/63415324/is-it-possible-for-a-pod-running-in-a-satrefulset-to-get-the-hostname-of-the-all
